### PR TITLE
Migrate to Jinja2 compiler syntax

### PR DESCRIPTION
**Pull request by nehaljwani**
Checklist
* [ ] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy`
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by peterjc** [comment]
Hmm, ci/circleci: build_linux_python2.7 failure looks like some sort of missing dependency...

```
import: 'backports'
import: 'backports.lzma'
+ python -m unittest discover -s test
E
======================================================================
ERROR: test_lzma (unittest.loader.ModuleImportFailure)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_lzma
Traceback (most recent call last):
  File "/home/conda/feedstock_root/build_artifacts/backports.lzma_1538477047839/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib/python2.7/unittest/loader.py", line 254, in _find_tests
    module = self._get_module_from_name(name)
  File "/home/conda/feedstock_root/build_artifacts/backports.lzma_1538477047839/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/lib/python2.7/unittest/loader.py", line 232, in _get_module_from_name
    __import__(name)
  File "/home/conda/feedstock_root/build_artifacts/backports.lzma_1538477047839/test_tmp/test/test_lzma.py", line 16, in <module>
    from future.backports.test.support import _4G, TESTFN, import_module, bigmemtest, run_unittest, unlink
ImportError: No module named future.backports.test.support


----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (errors=1)
```

**Comment by peterjc** [comment]
Is this (#17) meant to replace #13?

**Comment by nehaljwani** [comment]
Well, I am just testing at this point. I didn't have write access to the bot's branch, so I had to open a new PR.

**Comment by peterjc** [comment]
Ah - a separate PR makes sense - I was wondering how people normally debugged these automated pull requests...

Anyway, quoting http://python-future.org/changelog.html#changes-in-version-0-14-2-2014-11-21 

> Changes in version 0.14.2 (2014-11-21)
> This is a bug-fix release:
> ...
> Tests: don’t rely on presence of test.test_support on Py2 or test.support on Py3 (Issue #109)

Further digging into that needed to work out what the significance of that is for us - but hopefully all we need is to declare ``future`` as a Python 2.7 run time dependency (as in your last commit).

**Comment by peterjc** [comment]
Looking good, ci/circleci: build_linux_python2.7 now passes - waiting for the AppVeyor results

**Comment by nehaljwani** [comment]
Yay! All CI builds passed ;-)

**Comment by jakirkham** [comment]
Thanks for resurrecting this and pulling it across the finish line, @nehaljwani. 😄

**Comment by nehaljwani** [comment]
This was buried deep within my pending emails list.

**Comment by jakirkham** [comment]
Should have added feel free to add yourself as a maintainer if you like, @nehaljwani. The Windows build is largely thanks to your work.

**Pull request merged**
