### PR TITLE
Skip on Python 3.3 onwards (where part of Python)

### PR DESCRIPTION
**Pull request by peterjc**
This is a backport of Python 3.3's 'lzma' module for XZ/LZMA compressed files.

I can only think of two reasons to install the back port on Python 3.3 or later:

1. if your Python was compiled without lzma, which should not happen with conda.
2. for testing for a difference in behaviour between the backport and the upstream library.
 
The later is a corner case, and to me not worth the pain in getting this recipe to work on recent compilers.

Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [X] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by peterjc** [comment]
@conda-forge-admin, please rerender

**Comment by peterjc** [comment]
I believe this will effectively restrict the conda package to just Python 2.7, which will at some point be dropped all together. That is natural for a backport, and which point we can archive/delete this feedstock.

**Comment by jakirkham** [comment]
Yeah Python 2 is already dropped. So this would just disable it from building altogether

Interestingly see [one case]( https://github.com/conda-forge/wxpython-feedstock/blob/4da9b88e74f6d8e40a39f11566e12cd528095b06/recipe/meta.yaml#L57 ) where this being used without a constraint on Python version. Not sure if that is still needed ( cc @ocefpaf )

**Comment by ocefpaf** [comment]
> Interestingly see [one case](https://github.com/conda-forge/wxpython-feedstock/blob/4da9b88e74f6d8e40a39f11566e12cd528095b06/recipe/meta.yaml#L57) where this being used without a constraint on Python version. Not sure if that is still needed ( cc @ocefpaf )

That is probably wrong. I need to revisit the wxpython recipe :-/

**Comment by peterjc** [comment]
If conda-forge has dropped Python 2.7 already, I am inclined to archive the recipe and feedstock (rather than this PR restricting the version of Python)

**Comment by jakirkham** [comment]
> That is probably wrong. I need to revisit the wxpython recipe :-/

Ah ok. Wanted to check before we did something that would affect it 🙂

**Comment by peterjc** [comment]
wxpython-feedstock has been updated, so I think that means we can retire backports.lzma-feedstock now? I've not done this before for conda-forge...

**Comment by ocefpaf** [comment]
> wxpython-feedstock has been updated, so I think that means we can retire backports.lzma-feedstock now? I've not done this before for conda-forge...

Do we know that `wxpython`  was the only package using this? We probably need to keep for a while longer...

**Comment by ocefpaf** [comment]
Oh. Forget what I wrote above. This is only for py<33 and we do not build any of those. I'll archive this feedstock.
Thanks @peterjc!

**Pull request closed without merging**
